version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: increase
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "typescript"
        versions: [">=7"]
    groups:
      npm:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/tests/import/"
    versioning-strategy: increase
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "typescript"
        versions: [">=7"]
    groups:
      npm:
        patterns:
          - "*"
