# See https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: Publish package to GitHub Packages
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://npm.pkg.github.com"
          scope: "@cmahnke"
          always-auth: true
      - run: cat $NPM_CONFIG_USERCONFIG
      - run: npm ci
      - run: npm run build
      - run: |
          echo registry=https://npm.pkg.github.com/ > .npmrc
          echo always-auth=true >> .npmrc
          echo '//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}' >> .npmrc
      - run: npm publish --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
